version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    container_name: nuzlocke-companion-app

  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:5173"
    restart: unless-stopped
    container_name: nuzlocke-companion-test
