name: Deploy to Mac Mini (Test)

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restart Docker Container
        run: |
          export APP_PORT=3001
          export ENV_NAME=test
          docker compose -p nuzlocke-test up -d --build
