name: Deploy to Mac Mini (Preview)

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restart Docker Container
        run: |
          export APP_PORT=3001
          export ENV_NAME=${{ github.ref_name }}
          docker compose -p nuzlocke-preview up -d --build
